name: Test, Build, Push & Deploy

on:
  push:
    branches:
      - main

jobs:
  test-build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run tests
      run: |
        go test ./... -v

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.ECR_REPOSITORY }}:latest

    # ----------------- Deploy to Lambda -----------------
    - name: Update Lambda Function Code
      if: github.ref == 'refs/heads/main'
      env:
        FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        IMAGE_URI: ${{ secrets.ECR_REPOSITORY }}:latest
      run: |
        aws lambda update-function-code --function-name $FUNCTION_NAME --image-uri $IMAGE_URI
